---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: 'DOC è l"assistente NetApp ai disponibile su docs.NetApp.com. Risponde alle domande utilizzando solo il contenuto di questo sito. DOC non utilizza contenuti provenienti da altri siti NetApp o da Internet per rispondere alle domande.' 
---
= Panoramica dell'assistente ai-powered di NetApp generative
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOC è l'assistente NetApp ai disponibile su docs.NetApp.com. Risponde alle domande utilizzando solo il contenuto di questo sito. DOC non utilizza contenuti provenienti da altri siti NetApp o da Internet per rispondere alle domande.

DOC può creare risposte da domande precedenti, suggerire domande aggiuntive e spiegare come genera risposte. Si tratta di uno strumento prezioso per la navigazione nella documentazione di NetApp.



== Ambito e limitazioni

DOC può rispondere solo alle domande in base a contenuti selezionati pubblicati su docs.NetApp.com.


NOTE: Durante questa fase beta, Doc non è addestrato su tutti i contenuti docs.NetApp.com. DOC può rispondere a domande su contenuti quali, a titolo esemplificativo ma non esaustivo, contenuti ONTAP, BlueXP , StorageGRID, Keystone e SnapCenter. Se hai bisogno di informazioni Doc non ha, facci sapere.

* Se non si specifica una versione del prodotto, Doc risponde alle domande in base all'ultima versione pubblicata. Se necessario, è possibile specificare una versione precedente nella domanda.
* DOC non sa su quale pagina ti trovi quando fai una domanda. Per ottenere risultati ottimali, è necessario specificare i nomi e le versioni dei prodotti.
* DOC può chattare in lingue supportate su docs.NetApp.com, ma non è addestrato su versioni non in inglese.




== Scrittura di prompt validi

Seguite questi suggerimenti per la migliore esperienza con Doc.

Porre domande specifiche.:: Scrivere domande dettagliate e specificare il nome del prodotto, la versione e il tipo di interfaccia (GUI, API). Ad esempio:
+
--
[]
====
Quali passaggi è necessario seguire in Gestione sistema per eseguire l'aggiornamento da ONTAP 9,8 a ONTAP 9.12.1?

====
--
Richiedere le operazioni necessarie per completare un'attività.:: Chiedere a Doc di includere i passaggi per completare un processo. Invece di chiedere _come si installa il connettore BlueXP  senza Internet?_ provare:
+
--
[]
====
Quali sono i passaggi da seguire per installare il connettore BlueXP  senza Internet?

====
--
Suddivide in blocchi domande complesse.:: Suddividere le domande complesse in domande più piccole (note anche come _concatenamento_). DOC ricorda le domande precedenti e crea risposte più complesse mentre continui a parlare.
+
--
Per esempio, invece di chiedere a Doc _come si configura la protezione ransomware e le pianificazioni del backup in BlueXP ?_ TRY:

[]
====
Quali sono i passaggi per configurare la protezione ransomware in BlueXP ?

====
quindi chiedere:

[]
====
Quali sono i passaggi per configurare le pianificazioni di backup in BlueXP ?

====
--
Usare le virgolette.:: Racchiudere tra virgolette frasi composte da più parole. Questo aiuta Doc a riconoscere la frase come un singolo concetto, simile a come si potrebbe enfatizzarla in una conversazione con un umano.
+
--
Ad esempio, in questa domanda, _in che modo viene calcolata l'efficienza dello storage in ONTAP?_ Doc potrebbe pensare di dover porre in relazione a _storage_ e _efficienza_ come due parole non correlate. Provare invece:

[]
====
Come viene calcolata l'efficienza dello storage in ONTAP?

====
--
Rivedere la risposta del Doc.:: Dopo aver risposto, Doc fornisce informazioni su come ha generato la sua risposta. Ciò può darvi le idee per rifinire la vostra domanda per ottenere i risultati che desiderate.
Cancellare la cronologia chat:: Se si desidera modificare gli argomenti, cancellare la chat all'inizio. Poiché Doc ricorda le domande precedenti, le modifiche degli argomenti possono produrre risultati imprevisti.




== Feedback

Il tuo feedback ci aiuta a migliorare la risposta di Doc. Utilizza lo strumento di feedback nella finestra della chat del documento per farci sapere se le risposte sono accurate e utili o se hanno bisogno di miglioramenti. Puoi anche mailto:ng-doccomments@NetApp.com[contattaci] con domande o feedback.
