---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: 'DOC è il nostro assistente generativo basato sull"intelligenza artificiale su docs.netapp.com. DOC è progettato per rispondere alle domande sui prodotti NetApp, utilizzando contenuti pubblicati su docs.NetApp.com.' 
---
= Panoramica dell'assistente ai-powered di NetApp generative
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOC è il nostro assistente generativo basato sull'intelligenza artificiale su docs.netapp.com. DOC è progettato per rispondere alle domande sui prodotti NetApp, utilizzando contenuti pubblicati su docs.NetApp.com.

DOC può creare risposte da domande precedenti, suggerire domande aggiuntive e spiegare come genera risposte. Si tratta di uno strumento prezioso per la navigazione nella documentazione di NetApp.



== Ambito e limitazioni

DOC può rispondere solo alle domande in base a contenuti selezionati pubblicati su docs.NetApp.com.

* Doc risponde alle domande basandosi esclusivamente sull'ultima versione pubblicata di un prodotto. Ad esempio, se è disponibile documentazione per la versione 1.0 e la versione 2.0 di un prodotto, Doc fa riferimento solo alla documentazione 2.0 più recente.
* Per risultati ottimali, sii sempre specifico con i nomi dei prodotti. Doc sa a quale pagina ti trovi quando poni una domanda, ma è solo uno dei diversi fattori che Doc prende in considerazione quando formula una risposta.
* DOC può chattare in lingue supportate su docs.NetApp.com, ma non è addestrato su versioni non in inglese.




== Scrittura di prompt validi

Seguite questi suggerimenti per la migliore esperienza con Doc.

Porre domande specifiche.:: Scrivere domande dettagliate e specificare il nome del prodotto, la versione e il tipo di interfaccia (GUI, API). Ad esempio:
+
--
[]
====
Quali passaggi è necessario seguire in Gestione sistema per eseguire l'aggiornamento da ONTAP 9,8 a ONTAP 9.12.1?

====
--
Richiedere le operazioni necessarie per completare un'attività.:: Chiedi al dottore di includere i passaggi per completare un processo.  Invece di chiedere _Come faccio a installare l'agente NetApp Console senza Internet?_ prova:
+
--
[]
====
Quali passaggi devo seguire per installare l'agente NetApp Console senza Internet?

====
--
Suddivide in blocchi domande complesse.:: Suddividere le domande complesse in domande più piccole (note anche come _concatenamento_). DOC ricorda le domande precedenti e crea risposte più complesse mentre continui a parlare.
+
--
Ad esempio, invece di chiedere a Doc _Come faccio a configurare la protezione ransomware e le pianificazioni di backup nella console NetApp ?_ prova:

[]
====
Quali sono i passaggi per configurare la protezione ransomware nella console NetApp ?

====
quindi chiedere:

[]
====
Quali sono i passaggi per configurare le pianificazioni di backup nella console NetApp ?

====
--
Usare le virgolette.:: Racchiudere tra virgolette frasi composte da più parole. Questo aiuta Doc a riconoscere la frase come un singolo concetto, simile a come si potrebbe enfatizzarla in una conversazione con un umano.
+
--
Ad esempio, in questa domanda, _in che modo viene calcolata l'efficienza dello storage in ONTAP?_ Doc potrebbe pensare di dover porre in relazione a _storage_ e _efficienza_ come due parole non correlate. Provare invece:

[]
====
Come viene calcolata l'efficienza dello storage in ONTAP?

====
--
Rivedere la risposta del Doc.:: Dopo aver risposto, Doc fornisce informazioni su come ha generato la sua risposta. Ciò può darvi le idee per rifinire la vostra domanda per ottenere i risultati che desiderate.
Cancellare la cronologia chat:: Se vuoi cambiare argomento (ad esempio, per chiedere informazioni su un prodotto diverso), cancella la cronologia della chat per iniziare una nuova sessione. Se non cancelli la cronologia della chat prima di iniziare un nuovo argomento, potresti ottenere risultati imprecisi.




== Feedback

Stiamo lavorando per migliorare continuamente il documento. Inviaci un feedback nella finestra di chat del Doc. Facci sapere se le risposte del Doc sono accurate e utili o se sono incomplete o in qualche modo insufficienti. Puoi anche mailto:ng-doccomments@NetApp.com[contattaci] in caso di domande o dubbi riguardanti le capacità o le risposte del documento.
