---
settings:
  name: About docs.netapp.com
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Sui siti
    url: "/docs-netapp-com.html"
  - title: Informazioni su Doc (assistente ai-powered)
    url: "/doc-gen-ai-assistant.html"
  - title: Note legali
    url: "/legal-notices.html"
